# Generated by Django 4.2.5 on 2023-10-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_conversations_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversations',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='ConversationsID',
            new_name='Conversations',
        ),
    ]
