# Generated by Django 4.2.5 on 2023-10-09 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_messages_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Conversations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_set', to='users.conversations'),
        ),
    ]
